---
# Ansible include
#
# Deploy and setup btrfs snapshots statistics

- name: Deploy statistics script
  copy:
    src: 'statistics.sh'
    dest: '/opt/scripts/rsnapshot_btrfs-statistics.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'

- block:
  - name: Set cron vars for statistics
    cronvar:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      state: '{{ item.state|default("present") }}'
      cron_file: 'rsnapshot_btrfs-statistics'
    loop:
      - name: 'MAILTO'
        value: '{{ admin_mail }}'

  - name: Set cron jobs for statistics
    cron:
      name: '{{ item.name }}'
      state: '{{ item.state|default("present") }}'
      job: '{{ item.job }}'
      hour: '{{ item.hour|default(omit) }}'
      minute: '{{ item.minute|default(omit) }}'
      month: '{{ item.month|default(omit) }}'
      day: '{{ item.day|default(omit) }}'
      weekday: '{{ item.weekday|default(omit) }}'
      user: 'root'
      cron_file: 'rsnapshot_btrfs-statistics'
    loop:
      - name: Generate and send btrfs snapshots statistics
        job: >-
          /opt/scripts/rsnapshot_btrfs-statistics.sh |
          mail -s 'Odhady velikosti zaloh' '{{ rsnapshot_statistics_to|join("' '") }}'
        hour: 0
        minute: 0
        day: 1

  tags:
    - cron

...
